In [1]:
import yfinance as yf

In [2]:
t = yf.Ticker("GOOG")

In [3]:
t.income_stmt

,2024-12-31,2023-12-31,2022-12-31,2021-12-31
Tax Effect Of Unusual Items,3.401360e+08,-3.737710e+08,-1.035090e+09,2.002968e+09
Tax Rate For Calcs,1.640000e-01,1.390000e-01,1.590000e-01,1.620000e-01
Normalized EBITDA,1.333200e+11,1.006600e+11,9.167000e+10,9.115700e+10
Total Unusual Items,2.074000e+09,-2.689000e+09,-6.510000e+09,1.236400e+10
Total Unusual Items Excluding Goodwill,2.074000e+09,-2.689000e+09,-6.510000e+09,1.236400e+10
Net Income From Continuing Operation Net Minority Interest,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Reconciled Depreciation,1.531100e+10,1.194600e+10,1.347500e+10,1.244100e+10
Reconciled Cost Of Revenue,1.463060e+11,1.333320e+11,1.262030e+11,1.109390e+11
EBITDA,1.353940e+11,9.797100e+10,8.516000e+10,1.035210e+11
EBIT,1.200830e+11,8.602500e+10,7.168500e+10,9.108000e+10
Net Interest Income,4.214000e+09,3.557000e+09,1.817000e+09,1.153000e+09
Interest Expense,2.680000e+08,3.080000e+08,3.570000e+08,3.460000e+08
Interest Income,4.482000e+09,3.865000e+09,2.174000e+09,1.499000e+09
Normalized Income,9.838414e+10,7.611023e+10,6.544691e+10,6.567197e+10
Net Income From Continuing And Discontinued Operation,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Total Expenses,2.376280e+11,2.231010e+11,2.079940e+11,1.789230e+11
Total Operating Income As Reported,1.123900e+11,8.429300e+10,7.484200e+10,7.871400e+10
Diluted Average Shares,1.244700e+10,1.272200e+10,1.315900e+10,1.355348e+10
Basic Average Shares,1.231900e+10,1.263000e+10,1.306300e+10,1.335300e+10
Diluted EPS,8.040000e+00,5.800000e+00,4.560000e+00,5.610000e+00
Basic EPS,8.130000e+00,5.840000e+00,4.590000e+00,5.694000e+00
Diluted NI Availto Com Stockholders,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Net Income Common Stockholders,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Net Income,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Net Income Including Noncontrolling Interests,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Net Income Continuous Operations,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Tax Provision,1.969700e+10,1.192200e+10,1.135600e+10,1.470100e+10
Pretax Income,1.198150e+11,8.571700e+10,7.132800e+10,9.073400e+10
Other Income Expense,3.211000e+09,-2.133000e+09,-5.331000e+09,1.086700e+10
Other Non Operating Income Expenses,1.137000e+09,5.560000e+08,1.179000e+09,-1.497000e+09
Special Income Charges,-1.880000e+08,-6.280000e+08,-3.370000e+08,3.340000e+08
Write Off,1.880000e+08,6.280000e+08,3.370000e+08,-3.340000e+08
Earnings From Equity Interest,-1.880000e+08,-6.280000e+08,-3.370000e+08,3.340000e+08
Gain On Sale Of Security,2.262000e+09,-2.061000e+09,-6.173000e+09,1.203000e+10
Net Non Operating Interest Income Expense,4.214000e+09,3.557000e+09,1.817000e+09,1.153000e+09
Interest Expense Non Operating,2.680000e+08,3.080000e+08,3.570000e+08,3.460000e+08
Interest Income Non Operating,4.482000e+09,3.865000e+09,2.174000e+09,1.499000e+09
Operating Income,1.123900e+11,8.429300e+10,7.484200e+10,7.871400e+10
Operating Expense,9.132200e+10,8.976900e+10,8.179100e+10,6.798400e+10
Research And Development,4.932600e+10,4.542700e+10,3.950000e+10,3.156200e+10
Selling General And Administration,4.199600e+10,4.434200e+10,4.229100e+10,3.642200e+10
Selling And Marketing Expense,2.780800e+10,2.791700e+10,2.656700e+10,2.291200e+10
General And Administrative Expense,1.418800e+10,1.642500e+10,1.572400e+10,1.351000e+10
Other Gand A,1.418800e+10,1.642500e+10,1.572400e+10,1.351000e+10
Gross Profit,2.037120e+11,1.740620e+11,1.566330e+11,1.466980e+11
Cost Of Revenue,1.463060e+11,1.333320e+11,1.262030e+11,1.109390e+11
Total Revenue,3.500180e+11,3.073940e+11,2.828360e+11,2.576370e+11
Operating Revenue,3.500180e+11,3.073940e+11,2.828360e+11,2.576370e+11

In [4]:
t.balance_sheet

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Treasury Shares Number,NaN,0.000000e+00,NaN,NaN,NaN
Ordinary Shares Number,1.221100e+10,1.246000e+10,1.284900e+10,1.324242e+10,NaN
Share Issued,1.221100e+10,1.246000e+10,1.284900e+10,1.324242e+10,NaN
Total Debt,2.546100e+10,2.712100e+10,2.967900e+10,2.839500e+10,NaN
Tangible Book Value,2.931990e+11,2.541810e+11,2.271840e+11,2.272620e+11,NaN
...,...,...,...,...,...
Allowance For Doubtful Accounts Receivable,-8.790000e+08,-7.710000e+08,-7.540000e+08,-5.500000e+08,NaN
Gross Accounts Receivable,5.321900e+10,4.873500e+10,4.101200e+10,3.985400e+10,NaN
Cash Cash Equivalents And Short Term Investments,9.565700e+10,1.109160e+11,1.137620e+11,1.396490e+11,NaN
Other Short Term Investments,7.219100e+10,8.686800e+10,9.188300e+10,1.187040e+11,NaN
Cash And Cash Equivalents,2.346600e+10,2.404800e+10,2.187900e+10,2.094500e+10,NaN

In [5]:
t.cash_flow

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Free Cash Flow,7.276400e+10,6.949500e+10,6.001000e+10,6.701200e+10,NaN
Repurchase Of Capital Stock,-6.222200e+10,-6.150400e+10,-5.929600e+10,-5.027400e+10,NaN
Repayment Of Debt,-1.270100e+10,-1.155000e+10,-5.406800e+10,-2.143500e+10,NaN
Issuance Of Debt,1.358900e+10,1.079000e+10,5.287200e+10,2.019900e+10,NaN
Capital Expenditure,-5.253500e+10,-3.225100e+10,-3.148500e+10,-2.464000e+10,NaN
Income Tax Paid Supplemental Data,NaN,1.916400e+10,1.889200e+10,1.341200e+10,4.990000e+09
End Cash Position,2.346600e+10,2.404800e+10,2.187900e+10,2.094500e+10,NaN
Beginning Cash Position,2.404800e+10,2.187900e+10,2.094500e+10,2.646500e+10,NaN
Effect Of Exchange Rate Changes,-6.120000e+08,-4.210000e+08,-5.060000e+08,-2.870000e+08,NaN
Changes In Cash,3.000000e+07,2.590000e+09,1.440000e+09,-5.233000e+09,NaN
Financing Cash Flow,-7.973300e+10,-7.209300e+10,-6.975700e+10,-6.136200e+10,NaN
Cash Flow From Continuing Financing Activities,-7.973300e+10,-7.209300e+10,-6.975700e+10,-6.136200e+10,NaN
Net Other Financing Charges,1.154000e+09,8.000000e+06,3.500000e+07,3.100000e+08,NaN
Proceeds From Stock Option Exercised,-1.219000e+10,-9.837000e+09,-9.300000e+09,-1.016200e+10,NaN
Cash Dividends Paid,-7.363000e+09,0.000000e+00,0.000000e+00,NaN,NaN
Common Stock Dividend Paid,-7.363000e+09,0.000000e+00,0.000000e+00,NaN,NaN
Net Common Stock Issuance,-6.222200e+10,-6.150400e+10,-5.929600e+10,-5.027400e+10,NaN
Common Stock Payments,-6.222200e+10,-6.150400e+10,-5.929600e+10,-5.027400e+10,NaN
Net Issuance Payments Of Debt,8.880000e+08,-7.600000e+08,-1.196000e+09,-1.236000e+09,NaN
Net Long Term Debt Issuance,8.880000e+08,-7.600000e+08,-1.196000e+09,-1.236000e+09,NaN
Long Term Debt Payments,-1.270100e+10,-1.155000e+10,-5.406800e+10,-2.143500e+10,NaN
Long Term Debt Issuance,1.358900e+10,1.079000e+10,5.287200e+10,2.019900e+10,NaN
Investing Cash Flow,-4.553600e+10,-2.706300e+10,-2.029800e+10,-3.552300e+10,NaN
Cash Flow From Continuing Investing Activities,-4.553600e+10,-2.706300e+10,-2.029800e+10,-3.552300e+10,NaN
Net Other Investing Changes,-2.667000e+09,-1.051000e+09,1.589000e+09,5.410000e+08,NaN
Net Investment Purchase And Sale,1.259700e+10,6.734000e+09,1.656700e+10,-8.806000e+09,NaN
Sale Of Investment,1.043100e+11,8.761900e+10,9.797200e+10,1.292280e+11,NaN
Purchase Of Investment,-9.171300e+10,-8.088500e+10,-8.140500e+10,-1.380340e+11,NaN
Net Business Purchase And Sale,-2.931000e+09,-4.950000e+08,-6.969000e+09,-2.618000e+09,NaN
Purchase Of Business,-2.931000e+09,-4.950000e+08,-6.969000e+09,-2.618000e+09,NaN
Net PPE Purchase And Sale,-5.253500e+10,-3.225100e+10,-3.148500e+10,-2.464000e+10,NaN
Purchase Of PPE,-5.253500e+10,-3.225100e+10,-3.148500e+10,-2.464000e+10,NaN
Operating Cash Flow,1.252990e+11,1.017460e+11,9.149500e+10,9.165200e+10,NaN
Cash Flow From Continuing Operating Activities,1.252990e+11,1.017460e+11,9.149500e+10,9.165200e+10,NaN
Change In Working Capital,-8.406000e+09,-3.845000e+09,-2.235000e+09,-1.523000e+09,NaN
Change In Other Working Capital,-1.375000e+09,1.048000e+09,9.510000e+08,1.490000e+08,NaN
Change In Other Current Assets,-1.397000e+09,-2.143000e+09,-5.046000e+09,-1.846000e+09,NaN
Change In Payables And Accrued Expense,2.570000e+08,5.083000e+09,4.177000e+09,9.269000e+09,NaN
Change In Accrued Expense,-1.020000e+08,4.419000e+09,3.470000e+09,8.986000e+09,NaN
Change In Payable,3.590000e+08,6.640000e+08,7.070000e+08,2.830000e+08,NaN
Change In Account Payable,3.590000e+08,6.640000e+08,7.070000e+08,2.830000e+08,NaN
Change In Receivables,-5.891000e+09,-7.833000e+09,-2.317000e+09,-9.095000e+09,NaN
Changes In Account Receivables,-5.891000e+09,-7.833000e+09,-2.317000e+09,-9.095000e+09,NaN
Other Non Cash Items,3.419000e+09,4.330000e+09,3.483000e+09,-2.130000e+08,NaN
Stock Based Compensation,2.278500e+10,2.246000e+10,1.936200e+10,1.537600e+10,NaN
Deferred Tax,-5.257000e+09,-7.763000e+09,-8.081000e+09,1.808000e+09,NaN
Deferred Income Tax,-5.257000e+09,-7.763000e+09,-8.081000e+09,1.808000e+09,NaN
Depreciation Amortization Depletion,1.531100e+10,1.194600e+10,1.347500e+10,1.244100e+10,NaN
Depreciation And Amortization,1.531100e+10,1.194600e+10,1.347500e+10,1.244100e+10,NaN
Amortization Cash Flow,NaN,NaN,6.410000e+08,8.860000e+08,7.920000e+08
Amortization Of Intangibles,NaN,NaN,6.410000e+08,8.860000e+08,7.920000e+08
Depreciation,1.531100e+10,1.194600e+10,1.347500e+10,1.155500e+10,NaN
Operating Gains Losses,-2.671000e+09,8.230000e+08,5.519000e+09,-1.227000e+10,NaN
Gain Loss On Investment Securities,-2.671000e+09,8.230000e+08,5.519000e+09,-1.227000e+10,NaN
Net Income From Continuing Operations,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10,NaN

In [6]:
t.fast_info

lazy-loading dict with keys = ['currency', 'dayHigh', 'dayLow', 'exchange', 'fiftyDayAverage', 'lastPrice', 'lastVolume', 'marketCap', 'open', 'previousClose', 'quoteType', 'regularMarketPreviousClose', 'shares', 'tenDayAverageVolume', 'threeMonthAverageVolume', 'timezone', 'twoHundredDayAverage', 'yearChange', 'yearHigh', 'yearLow']

In [7]:
info = t.fast_info
info['timezone']

'America/New_York'

In [8]:
t.news

[{'id': 'a20ff3b1-6a94-446e-9935-288333b726d0',
  'content': {'id': 'a20ff3b1-6a94-446e-9935-288333b726d0',
   'contentType': 'STORY',
   'title': 'Stock market today: Dow, S&P 500, Nasdaq mixed with retail sales, inflation data in focus',
   'description': '',
   'summary': 'Markets are muted after a strong start to the week as investors take stock of a Fed-fueled rebound.',
   'pubDate': '2025-11-25T14:36:04Z',
   'displayTime': '2025-11-25T14:38:36Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-images/2019-12/441224f0-2925-11ea-96ff-875256a153fc',
    'originalWidth': 5184,
    'originalHeight': 3456,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/s5q0wy4rFCNaQwBbllMmUg--~B/aD0zNDU2O3c9NTE4NDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-images/2019-12/441224f0-2925-11ea-96ff-875256a153fc',
      'width': 5184,
      'height': 3456,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/Kx6mqJ4RcN_ZU0WtYBKHkQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-images/2019-12/441224f0-2925-11ea-96ff-875256a153fc',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-nasdaq-mixed-with-retail-sales-inflation-data-in-focus-143604082.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-nasdaq-mixed-with-retail-sales-inflation-data-in-focus-143604082.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': {'storylineItems': [{'content': {'id': '640e9262-2a37-40bc-80a9-b45410bb88eb',
       'contentType': 'STORY',
       'isHosted': True,
       'title': 'Nvidia stock falls after report says Google, Meta in talks for multibillion-dollar AI chip deal',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-11/aec4e4a0-be47-11f0-a96b-41f33604345d',
        'originalWidth': 5196,
        'originalHeight': 3464,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance',
        'sourceId': 'yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/news/nvidia-stock-falls-after-report-says-google-meta-in-talks-for-multibillion-dollar-ai-chip-deal-143725770.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/nvidia-stock-falls-after-report-says-google-meta-in-talks-for-multibillion-dollar-ai-chip-deal-143725770.html'}}},
     {'content': {'id': '2e8119d9-4781-30f6-b07f-aa298b4d0d19',
       'contentType': 'VIDEO',
       'isHosted': True,
       'title': "Retail sales, Alphabet chips for Meta, Dick's earnings: 3 Things",
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-11/af816f90-ca08-11f0-8afa-c282885024e4',
        'originalWidth': 7000,
        'originalHeight': 3941,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance Video',
        'sourceId': 'video.yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/video/retail-sales-alphabet-chips-meta-141206404.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/retail-sales-alphabet-chips-meta-141206404.html'}}}]}}},
 {'id': '5dbc03f7-82f0-3221-8276-399a77064418',
  'content': {'id': '5dbc03f7-82f0-3221-8276-399a77064418',
   'contentType': 'VIDEO',
   'title': "The AI stocks still rising (it's not just GOOGL)",
   'description': '<p>While big names including Nvidia (<a data-i13n="cpos:1;pos:1" href="https://finance.yahoo.com/quote/NVDA">NVDA</a>) and Oracle (<a data-i13n="cpos:2;pos:1" href="https://finance.yahoo.com/quote/ORCL">ORCL</a>) are struggling to reverse the latest selloff in AI stocks, many others are benefitting from renewed momentum and growth following their latest results. Ramzan Karmali explains why tech companies including Broadcom (<a data-i13n="cpos:3;pos:1" href="https://finance.yahoo.com/quote/AVGO">AVGO</a>), Symbotic (<a data-i13n="cpos:4;pos:1" href="https://finance.yahoo.com/quote/SYM">SYM</a>), Zoom (<a data-i13n="cpos:5;pos:1" href="https://finance.yahoo.com/quote/ZM">ZM</a>), and China\'s robotaxis from Pony AI (<a data-i13n="cpos:6;pos:1" href="https://finance.yahoo.com/quote/PONY">PONY</a>), are getting investors excited.</p>\n<p></p>\n<p>For more live coverage of the markets, watch the full episode of <em>Market Sunrise</em> and visit<a data-i13n="cpos:7;pos:1" href="https://finance.yahoo.com/"> <ins>Yahoo Finance</ins></a>.</p>',
   'summary': "While big names including Nvidia (NVDA) and Oracle (ORCL) are struggling to reverse the latest selloff in AI stocks, many others are benefitting from renewed momentum and growth following their latest results. Ramzan Karmali explains why tech companies including Broadcom (AVGO), Symbotic (SYM), Zoom (ZM), and China's robotaxis from Pony AI (PONY), are getting investors excited.  For more live coverage of the markets, watch the full episode of Market Sunrise and visit Yahoo Finance.",
   'pubDate': '2025-11-25T13:04:21Z',
   'displayTime': '',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-11/214fc470-c9fd-11f0-b2f7-5345d0421f55',
    'originalWidth': 3000,
    'originalHeight': 1690,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/TgB9LgwyuHnju7dHuTkLwg--~B/aD0xNjkwO3c9MzAwMDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2025-11/214fc470-c9fd-11f0-b2f7-5345d0421f55',
      'width': 3000,
      'height': 1690,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/lVV_Sc8o1SqzwoqiOI90iQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-uploaded-images/2025-11/214fc470-c9fd-11f0-b2f7-5345d0421f55',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance Video',
    'url': 'https://finance.yahoo.com/'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/video/ai-stocks-still-rising-not-130421983.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/ai-stocks-still-rising-not-130421983.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': {'storylineItems': [{'content': {'id': '3e0a6c78-8109-312e-b52d-b34d508e408c',
       'contentType': 'VIDEO',
       'isHosted': True,
       'title': 'Google flexes its AI muscles',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-11/b7d5a960-c9fc-11f0-bc5e-fb088a93072e',
        'originalWidth': 4172,
        'originalHeight': 2349,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance Video',
        'sourceId': 'video.yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/video/google-flexes-ai-muscles-125950987.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/google-flexes-ai-muscles-125950987.html'}}},
     {'content': {'id': '60bbc4a7-8d67-3aab-8c0e-69a774562840',
       'contentType': 'VIDEO',
       'isHosted': True,
       'title': 'Alphabet rises on Gemini 3, Anthropic unveils Claude Opus 4.5',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-11/021c4bc0-c979-11f0-b69f-25b6d2bc72f0',
        'originalWidth': 6000,
        'originalHeight': 3378,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance Video',
        'sourceId': 'video.yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/video/alphabet-rises-gemini-3-anthropic-210441000.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/alphabet-rises-gemini-3-anthropic-210441000.html'}}}]}}},
 {'id': 'd0c91709-679a-4374-b20d-e21d75b49e24',
  'content': {'id': 'd0c91709-679a-4374-b20d-e21d75b49e24',
   'contentType': 'STORY',
   'title': 'Stock market today: Nasdaq sees biggest jump since May, S&P 500 soars as Alphabet, Tesla lead tech rally',
   'description': '',
   'summary': 'Spirits are upbeat after a Fed official signaled support for a December rate cut.',
   'pubDate': '2025-11-24T21:01:14Z',
   'displayTime': '2025-11-24T21:04:21Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-images/2019-12/441224f0-2925-11ea-96ff-875256a153fc',
    'originalWidth': 5184,
    'originalHeight': 3456,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/s5q0wy4rFCNaQwBbllMmUg--~B/aD0zNDU2O3c9NTE4NDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-images/2019-12/441224f0-2925-11ea-96ff-875256a153fc',
      'width': 5184,
      'height': 3456,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/Kx6mqJ4RcN_ZU0WtYBKHkQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-images/2019-12/441224f0-2925-11ea-96ff-875256a153fc',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance',
    'url': 'http://finance.yahoo.com/'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/live/stock-market-today-nasdaq-sees-biggest-jump-since-may-sp-500-soars-as-alphabet-tesla-lead-tech-rally-210114487.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/live/stock-market-today-nasdaq-sees-biggest-jump-since-may-sp-500-soars-as-alphabet-tesla-lead-tech-rally-210114487.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': {'storylineItems': [{'content': {'id': '6a96aeb8-906c-42f3-a56e-5870db126af6',
       'contentType': 'STORY',
       'isHosted': True,
       'title': "Anthropic launches Claude Opus 4.5 as Google's Gemini 3 gains big backers",
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-06/105e9950-52c7-11f0-b97f-65f0ea06cf2d',
        'originalWidth': 7035,
        'originalHeight': 4692,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance',
        'sourceId': 'yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/news/anthropic-launches-claude-opus-45-as-googles-gemini-3-gains-big-backers-191645109.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/anthropic-launches-claude-opus-45-as-googles-gemini-3-gains-big-backers-191645109.html'}}},
     {'content': {'id': '0c089676-3006-398e-932a-9169ab689655',
       'contentType': 'VIDEO',
       'isHosted': True,
       'title': 'Alphabet stock pops on Gemini 3 rollout, Inspire Medical surges',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-11/7d5c1800-c966-11f0-b684-0ad83c1a4d15',
        'originalWidth': 4000,
        'originalHeight': 2246,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance Video',
        'sourceId': 'video.yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/video/alphabet-stock-pops-gemini-3-190616874.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/alphabet-stock-pops-gemini-3-190616874.html'}}}]}}},
 {'id': '6f086999-3a7d-3792-a9c8-0ede14eb0d79',
  'content': {'id': '6f086999-3a7d-3792-a9c8-0ede14eb0d79',
   'contentType': 'VIDEO',
   'title': 'Amazon to spend $50B on AI, Google & Broadcom stocks surge',
   'description': '<p>Yahoo Finance\'s <a data-i13n="cpos:1;pos:1" href="https://finance.yahoo.com/author/john-hyland/">John Hyland</a> tracks Monday\'s top moving stocks and biggest market stories in this Market Minute, including Amazon\'s (<a data-i13n="cpos:2;pos:1" href="https://finance.yahoo.com/quote/AMZN">AMZN</a>) planned $50 billion investment into artificial intelligence (AI) initiatives, Broadcom (<a data-i13n="cpos:3;pos:1" href="https://finance.yahoo.com/quote/AVGO">AVGO</a>) and Alphabet (<a data-i13n="cpos:4;pos:1" href="https://finance.yahoo.com/quote/GOOG">GOOG</a>, <a data-i13n="cpos:5;pos:1" href="https://finance.yahoo.com/quote/GOOGL">GOOGL</a>) stocks climbing, and Kohl\'s (<a data-i13n="cpos:6;pos:1" href="https://finance.yahoo.com/quote/KSS">KSS</a>) new CEO.</p>\n<p>Stay up to date on the latest market action, minute-by-minute, with\xa0<a data-i13n="cpos:7;pos:1" href="https://finance.yahoo.com/videos/series/market-minute/">Yahoo Finance\'s Market Minute.</a></p>',
   'summary': "Yahoo Finance's John Hyland tracks Monday's top moving stocks and biggest market stories in this Market Minute, including Amazon's (AMZN) planned $50 billion investment into artificial intelligence (AI) initiatives, Broadcom (AVGO) and Alphabet (GOOG, GOOGL) stocks climbing, and Kohl's (KSS) new CEO. Stay up to date on the latest market action, minute-by-minute, with&nbsp;Yahoo Finance's Market Minute.",
   'pubDate': '2025-11-24T18:14:18Z',
   'displayTime': '',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-11/5221c180-c961-11f0-bbb6-996674dda458',
    'originalWidth': 2402,
    'originalHeight': 1351,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/4BZhZcykacCMRHxLTdr4PQ--~B/aD0xMzUxO3c9MjQwMjthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2025-11/5221c180-c961-11f0-bbb6-996674dda458',
      'width': 2402,
      'height': 1351,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/.L9pmJ_GwIXbM8Tr.R5f2g--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-uploaded-images/2025-11/5221c180-c961-11f0-bbb6-996674dda458',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance Video',
    'url': 'https://finance.yahoo.com/'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/video/amazon-spend-50b-ai-google-181418899.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/amazon-spend-50b-ai-google-181418899.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': {'storylineItems': [{'content': {'id': '5db205d2-e7b8-4324-b640-4edc0e8ec3a4',
       'contentType': 'STORY',
       'isHosted': True,
       'title': 'Amazon to invest $50 billion in data centers to power US government AI efforts',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-11/ad009680-c957-11f0-9eff-fbf2a9825258',
        'originalWidth': 4605,
        'originalHeight': 3070,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance',
        'sourceId': 'yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/news/amazon-to-invest-50-billion-in-data-centers-to-power-us-government-ai-efforts-181259967.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/amazon-to-invest-50-billion-in-data-centers-to-power-us-government-ai-efforts-181259967.html'}}},
     {'content': {'id': '1495545d-5dfe-3858-aad1-68c0897fb1c7',
       'contentType': 'VIDEO',
       'isHosted': True,
       'title': 'Alphabet stock rallies, Six Flags names new CEO',
       'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-11/b24eb0b0-c955-11f0-8df1-1731539dc083',
        'originalWidth': 4964,
        'originalHeight': 2794,
        'caption': '',
        'resolutions': None},
       'provider': {'displayName': 'Yahoo Finance Video',
        'sourceId': 'video.yahoofinance.com'},
       'previewUrl': None,
       'providerContentUrl': '',
       'canonicalUrl': {'url': 'https://finance.yahoo.com/video/alphabet-stock-rallies-six-flags-165040139.html'},
       'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/alphabet-stock-rallies-six-flags-165040139.html'}}}]}}},
 {'id': '3eeef37a-6f2e-300e-a683-e2550c7519ad',
  'content': {'id': '3eeef37a-6f2e-300e-a683-e2550c7519ad',
   'contentType': 'STORY',
   'title': 'Google Parent Alphabet Drops $100 Million On Celero: The $140 Million Startup Ending AI Data Center Bottlenecks',
   'description': '',
   'summary': 'Semiconductor startup Celero Communications announced on Nov. 17 that it closed $140 million in total funding to tackle one of artificial intelligence’s most critical infrastructure challenges: bandwidth limits in AI data centers. Celero Communications pulled in $100 million during its Series B round, with CapitalG, Alphabet’s (NASDAQ:GOOG, GOOGL)) independent growth fund, serving as lead investor. The Irvine, California-based company previously raised $40 million across seed and Series A rounds',
   'pubDate': '2025-11-25T14:46:09Z',
   'displayTime': '2025-11-25T14:46:09Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/Benzinga/fec30ec2b61c305bfd49dc96630e30c2',
    'originalWidth': 1000,
    'originalHeight': 563,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/9mTrmYc7BO2N.VS2mhPTAg--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Benzinga/fec30ec2b61c305bfd49dc96630e30c2',
      'width': 1000,
      'height': 563,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/POzL3HVwOdY1E2bzUge.yA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/Benzinga/fec30ec2b61c305bfd49dc96630e30c2',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Benzinga', 'url': 'http://www.benzinga.com/'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/news/google-parent-alphabet-drops-100-144609325.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/google-parent-alphabet-drops-100-144609325.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'c7940a9e-d653-3c4a-9467-c4e4565adb0b',
  'content': {'id': 'c7940a9e-d653-3c4a-9467-c4e4565adb0b',
   'contentType': 'STORY',
   'title': 'Google In Talks To Offer Its AI Chips To Meta; Nvidia, AMD Fall',
   'description': '',