In [1]:
import yfinance as yf

In [2]:
# 定义企业上市（股票）代码
dat = yf.Ticker("PDD")

In [3]:
# 简单获取近1年的日交易数据
dat.history(period="1y")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-08-09 00:00:00-04:00,138.759995,139.259995,136.949997,138.039993,6331800,0.0,0.0
2024-08-12 00:00:00-04:00,138.039993,143.259995,137.100006,142.470001,7702300,0.0,0.0
2024-08-13 00:00:00-04:00,143.929993,145.000000,142.860001,144.020004,5726800,0.0,0.0
2024-08-14 00:00:00-04:00,144.899994,145.000000,141.220001,141.979996,6048800,0.0,0.0
2024-08-15 00:00:00-04:00,144.000000,146.690002,143.570007,145.080002,7992800,0.0,0.0
...,...,...,...,...,...,...,...
2025-08-04 00:00:00-04:00,111.820000,113.059998,111.440002,112.040001,3842600,0.0,0.0
2025-08-05 00:00:00-04:00,112.639999,114.459999,112.250000,112.620003,3181900,0.0,0.0
2025-08-06 00:00:00-04:00,113.650002,115.440002,112.820000,113.940002,4374100,0.0,0.0
2025-08-07 00:00:00-04:00,114.440002,115.849998,114.169998,114.190002,5153900,0.0,0.0
2025-08-08 00:00:00-04:00,114.059998,114.970001,113.129997,114.260002,4327600,0.0,0.0

In [4]:
# 了解公司核心数据及概况
dat.info

{'address1': '25 St Stephen’s Green',
 'address2': 'First Floor Dublin 2',
 'city': 'Dublin',
 'zip': 'D02 XF99',
 'country': 'Ireland',
 'phone': '353 1 539 7938',
 'website': 'https://www.pddholdings.com',
 'industry': 'Internet Retail',
 'industryKey': 'internet-retail',
 'industryDisp': 'Internet Retail',
 'sector': 'Consumer Cyclical',
 'sectorKey': 'consumer-cyclical',
 'sectorDisp': 'Consumer Cyclical',
 'longBusinessSummary': 'PDD Holdings Inc., a multinational commerce group that owns and operates a portfolio of businesses. It operates Pinduoduo platform which provides various product categories, including agricultural produce, apparel, shoes, bags, mother and childcare products, food and beverages, consumer electronics, electronic appliances, furniture and household goods, cosmetics and other personal care items, sports and fitness, and auto accessories; and Temu, an online platform, which enables merchants to streamline their manufacturing and commercial operations. The company was formerly known as Pinduoduo Inc. and changed its name to PDD Holdings Inc. in February 2023. PDD Holdings Inc. was incorporated in 2015 and is based in Dublin, Ireland.',
 'fullTimeEmployees': 23465,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Lei  Chen',
   'age': 44,
   'title': 'General Counsel, Co-CEO & Chairman',
   'yearBorn': 1980,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jiazhen  Zhao',
   'age': 40,
   'title': 'Co-CEO & Executive Director',
   'yearBorn': 1984,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jun  Liu',
   'age': 41,
   'title': 'Vice President of Finance',
   'yearBorn': 1983,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Junyun  Xiao',
   'age': 44,
   'title': 'Senior Vice President of Operation',
   'yearBorn': 1980,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Zhenwei  Zheng',
   'age': 40,
   'title': 'Senior Vice President of Product Development',
   'yearBorn': 1984,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'David  Liu',
   'title': 'Vice President of Strategy',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Peng  Cheng',
   'title': 'IR Director',
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 114.19,
 'open': 114.055,
 'dayLow': 113.1303,
 'dayHigh': 114.9731,
 'regularMarketPreviousClose': 114.19,
 'regularMarketOpen': 114.055,
 'regularMarketDayLow': 113.1303,
 'regularMarketDayHigh': 114.9731,
 'payoutRatio': 0.0,
 'beta': 0.41,
 'trailingPE': 12.259657,
 'forwardPE': 8.109298,
 'volume': 4326495,
 'regularMarketVolume': 4326495,
 'averageVolume': 7668019,
 'averageVolume10days': 5343120,
 'averageDailyVolume10Day': 5343120,
 'bid': 97.78,
 'ask': 130.42,
 'bidSize': 1,
 'askSize': 1,
 'marketCap': 162209218560,
 'fiftyTwoWeekLow': 87.11,
 'fiftyTwoWeekHigh': 155.67,
 'priceToSalesTrailing12Months': 0.40280792,
 'fiftyDayAverage': 106.5486,
 'twoHundredDayAverage': 109.7613,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 282929168384,
 'profitMargins': 0.24629,
 'floatShares': 3053828589,
 'sharesOutstanding': 1419650048,
 'sharesShort': 23716745,
 'sharesShortPriorMonth': 32147681,
 'sharesShortPreviousMonthDate': 1749772800,
 'dateShortInterest': 1752537600,
 'sharesPercentSharesOut': 0.0167,
 'heldPercentInsiders': 2.0000001e-05,
 'heldPercentInstitutions': 0.32217,
 'shortRatio': 4.27,
 'shortPercentOfFloat': 0.0278,
 'impliedSharesOutstanding': 1388770048,
 'bookValue': 236.863,
 'priceToBook': 0.48238856,
 'lastFiscalYearEnd': 1735603200,
 'nextFiscalYearEnd': 1767139200,
 'mostRecentQuarter': 1743379200,
 'earningsQuarterlyGrowth': -0.473,
 'netIncomeToCommon': 99178512384,
 'trailingEps': 9.32,
 'forwardEps': 14.09,
 'enterpriseToRevenue': 0.703,
 'enterpriseToEbitda': 2.851,
 '52WeekChange': -0.19800657,
 'SandP52WeekChange': 0.19554341,
 'quoteType': 'EQUITY',
 'currentPrice': 114.26,
 'targetHighPrice': 165.24626,
 'targetLowPrice': 87.05445,
 'targetMeanPrice': 125.59361,
 'targetMedianPrice': 125.193214,
 'recommendationMean': 1.8,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 35,
 'totalCash': 364500844544,
 'totalCashPerShare': 65.466,
 'ebitda': 99224166400,
 'totalDebt': 11252827136,
 'quickRatio': 1.915,
 'currentRatio': 2.273,
 'totalRevenue': 402696208384,
 'debtToEquity': 3.413,
 'revenuePerShare': 290.201,
 'returnOnAssets': 0.1356,
 'returnOnEquity': 0.36169997,
 'grossProfits': 240543432704,
 'freeCashflow': 103603159040,
 'operatingCashflow': 116379058176,
 'earningsGrowth': -0.475,
 'revenueGrowth': 0.102,
 'grossMargins': 0.59733003,
 'ebitdaMargins': 0.2464,
 'operatingMargins': 0.16813,
 'financialCurrency': 'CNY',
 'symbol': 'PDD',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'postMarketTime': 1754697579,
 'regularMarketTime': 1754683201,
 'regularMarketChangePercent': 0.0613011,
 'regularMarketPrice': 114.26,
 'corporateActions': [],
 'exchange': 'NMS',
 'messageBoardId': 'finmb_572577901',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'longName': 'PDD Holdings Inc.',
 'prevName': 'Pinduoduo Inc.',
 'nameChangeDate': '2025-08-09',
 'averageAnalystRating': '1.8 - Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 1532611800000,
 'postMarketChangePercent': -0.0962722,
 'postMarketPrice': 114.15,
 'postMarketChange': -0.110001,
 'regularMarketChange': 0.0699997,
 'regularMarketDayRange': '113.1303 - 114.9731',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 7668019,
 'shortName': 'PDD Holdings Inc.',
 'marketState': 'CLOSED',
 'fiftyTwoWeekLowChange': 27.150002,
 'fiftyTwoWeekLowChangePercent': 0.31167492,
 'fiftyTwoWeekRange': '87.11 - 155.67',
 'fiftyTwoWeekHighChange': -41.409996,
 'fiftyTwoWeekHighChangePercent': -0.26601142,
 'fiftyTwoWeekChangePercent': -19.800657,
 'earningsTimestamp': 1748341834,
 'earningsTimestampStart': 1756180800,
 'earningsTimestampEnd': 1756180800,
 'earningsCallTimestampStart': 1748345400,
 'earningsCallTimestampEnd': 1748345400,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 9.32,
 'epsForward': 14.09,
 'epsCurrentYear': 60.75376,
 'priceEpsCurrentYear': 1.8807067,
 'fiftyDayAverageChange': 7.711403,
 'fiftyDayAverageChangePercent': 0.072374515,
 'twoHundredDayAverageChange': 4.498703,
 'twoHundredDayAverageChangePercent': 0.04098624,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'displayName': 'PDD',
 'trailingPegRatio': 1.4211}

In [5]:
# 企业重要事件日历
dat.calendar

{'Earnings Date': [datetime.date(2025, 8, 26)],
 'Earnings High': 18.48,
 'Earnings Low': 9.0436,
 'Earnings Average': 14.79894,
 'Revenue High': 108773000000,
 'Revenue Low': 95294231120,
 'Revenue Average': 103195938270}

In [6]:
# 企业季度营收数据
dat.quarterly_income_stmt

,2025-03-31,2024-12-31,2024-09-30,2024-06-30,2024-03-31,2023-12-31
Tax Effect Of Unusual Items,-5.613604e+07,1.349433e+08,-7.881230e+07,9.371067e+06,3.282577e+07,NaN
Tax Rate For Calcs,2.318330e-01,1.568150e-01,1.439910e-01,1.557560e-01,1.530210e-01,NaN
Normalized EBITDA,1.632770e+10,3.155218e+10,2.972714e+10,3.791339e+10,2.575914e+10,NaN
Total Unusual Items,-2.421400e+08,8.605260e+08,-5.473430e+08,6.016500e+07,2.145180e+08,NaN
Total Unusual Items Excluding Goodwill,-2.421400e+08,8.605260e+08,-5.473430e+08,6.016500e+07,2.145180e+08,NaN
Net Income From Continuing Operation Net Minority Interest,1.474183e+10,2.744664e+10,2.498069e+10,3.200936e+10,2.799783e+10,NaN
Reconciled Cost Of Revenue,4.094710e+10,4.779838e+10,3.970921e+10,3.369810e+10,3.269469e+10,NaN
EBITDA,1.608556e+10,3.241271e+10,2.917980e+10,3.797355e+10,2.597365e+10,NaN
EBIT,1.608556e+10,3.241271e+10,2.917980e+10,3.797355e+10,2.597365e+10,NaN
Net Interest Income,2.231250e+08,5.233232e+09,5.416080e+09,4.855592e+09,5.048589e+09,NaN
Interest Expense,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8155000.0
Interest Income,2.231250e+08,5.233232e+09,5.416080e+09,4.855592e+09,5.048589e+09,NaN
Normalized Income,1.492783e+10,2.672105e+10,2.544922e+10,3.195856e+10,2.781613e+10,NaN
Net Income From Continuing And Discontinued Operation,1.474183e+10,2.744664e+10,2.498069e+10,3.200936e+10,2.799783e+10,NaN
Total Expenses,7.958661e+10,8.501789e+10,7.506194e+10,6.449500e+10,6.083841e+10,NaN
Total Operating Income As Reported,1.608556e+10,2.559222e+10,2.429246e+10,3.256454e+10,2.597365e+10,NaN
Diluted Average Shares,1.483081e+09,1.481320e+09,1.477448e+09,1.481415e+09,1.476755e+09,NaN
Basic Average Shares,1.391951e+09,1.389194e+09,1.385908e+09,1.383449e+09,1.377420e+09,NaN
Diluted EPS,9.960000e+00,1.852000e+01,1.692000e+01,2.160000e+01,1.896000e+01,NaN
Basic EPS,1.060000e+01,1.976000e+01,1.804000e+01,2.312000e+01,2.032000e+01,NaN
Diluted NI Availto Com Stockholders,1.474183e+10,2.744664e+10,2.498069e+10,3.200936e+10,2.799783e+10,NaN
Net Income Common Stockholders,1.474183e+10,2.744664e+10,2.498069e+10,3.200936e+10,2.799783e+10,NaN
Net Income,1.474183e+10,2.744664e+10,2.498069e+10,3.200936e+10,2.799783e+10,NaN
Net Income Including Noncontrolling Interests,1.474183e+10,2.744664e+10,2.498069e+10,3.200936e+10,2.799783e+10,NaN
Net Income Continuous Operations,1.474183e+10,2.744664e+10,2.498069e+10,3.200936e+10,2.799783e+10,NaN
Earnings From Equity Interest Net Of Tax,-1.051800e+08,1.167250e+08,2.513000e+06,-4.958300e+07,-5.243000e+07,NaN
Tax Provision,4.480831e+09,5.082796e+09,4.201620e+09,5.914613e+09,5.067752e+09,NaN
Pretax Income,1.932784e+10,3.241271e+10,2.917980e+10,3.797355e+10,3.311801e+10,NaN
Other Income Expense,3.019152e+09,1.587261e+09,-5.287370e+08,5.534230e+08,2.095766e+09,NaN
Other Non Operating Income Expenses,3.261292e+09,7.267350e+08,1.860600e+07,4.932580e+08,1.881248e+09,NaN
Gain On Sale Of Security,-2.421400e+08,8.605260e+08,-5.473430e+08,6.016500e+07,2.145180e+08,NaN
Net Non Operating Interest Income Expense,2.231250e+08,5.233232e+09,5.416080e+09,4.855592e+09,5.048589e+09,NaN
Interest Expense Non Operating,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8155000.0
Interest Income Non Operating,2.231250e+08,5.233232e+09,5.416080e+09,4.855592e+09,5.048589e+09,NaN
Operating Income,1.608556e+10,2.559222e+10,2.429246e+10,3.256454e+10,2.597365e+10,NaN
Operating Expense,3.863951e+10,3.721952e+10,3.535273e+10,3.079690e+10,2.814372e+10,NaN
Research And Development,3.577828e+09,3.777178e+09,3.063353e+09,2.909210e+09,2.909620e+09,NaN
Selling General And Administration,3.506168e+10,3.344234e+10,3.228938e+10,2.788769e+10,2.523410e+10,NaN
Selling And Marketing Expense,3.340274e+10,3.135694e+10,3.048380e+10,2.604914e+10,2.341066e+10,NaN
General And Administrative Expense,1.658943e+09,2.085396e+09,1.805576e+09,1.838550e+09,1.823445e+09,NaN
Other Gand A,1.658943e+09,2.085396e+09,1.805576e+09,1.838550e+09,1.823445e+09,NaN
Gross Profit,5.472508e+10,6.281173e+10,5.964519e+10,6.336143e+10,5.411737e+10,NaN
Cost Of Revenue,4.094710e+10,4.779838e+10,3.970921e+10,3.369810e+10,3.269469e+10,NaN
Total Revenue,9.567218e+10,1.106101e+11,9.935440e+10,9.705953e+10,8.681206e+10,NaN
Operating Revenue,9.567218e+10,1.106101e+11,9.935440e+10,9.705953e+10,8.681206e+10,NaN