In [12]:
import yfinance as yf
import time
from datetime import datetime

In [13]:
# 实例1：单次获取
symbol = "000001.SS"  # 可改为 000001.SS（上证）、GOOGL、BTC-USD 等
ticker = yf.Ticker(symbol)
info = ticker.fast_info
info

lazy-loading dict with keys = ['currency', 'dayHigh', 'dayLow', 'exchange', 'fiftyDayAverage', 'lastPrice', 'lastVolume', 'marketCap', 'open', 'previousClose', 'quoteType', 'regularMarketPreviousClose', 'shares', 'tenDayAverageVolume', 'threeMonthAverageVolume', 'timezone', 'twoHundredDayAverage', 'yearChange', 'yearHigh', 'yearLow']

In [14]:
info.open

4079.70751953125

In [15]:
price = info.last_price      # 最新价
volume = info.last_volume    # 最新成交量（可能为 None）
high = info.day_high
low = info.day_low
print(f"{symbol} 最新价: {price}, 成交量: {volume}, 最低价：{high}, 最高价：{low}")

000001.SS 最新价: 4039.75048828125, 成交量: 974116156, 最低价：4103.4072265625, 最高价：4024.8603515625

In [ ]:
# 实例2：轮询获取
symbols = ["000001.SS"]
interval = 5  # 秒

while True:
    for symbol in symbols:
        try:
            ticker = yf.Ticker(symbol)
            info = ticker.fast_info
            price = info.last_price
            volume = info.last_volume or 0
            print(f"[{datetime.now().strftime('%H:%M:%S')}] {symbol} -> {price} | Vol: {volume}")
        except Exception as e:
            print(f"{symbol} 获取失败: {e}")
    time.sleep(interval)

[14:51:46] 000001.SS -> 4031.30224609375 | Vol: 457904760
[14:51:52] 000001.SS -> 4030.74560546875 | Vol: 540318960
[14:51:58] 000001.SS -> 4030.74560546875 | Vol: 540318960
[14:52:04] 000001.SS -> 4030.802001953125 | Vol: 582180060
[14:52:10] 000001.SS -> 4030.802001953125 | Vol: 582180060
[14:52:16] 000001.SS -> 4031.072021484375 | Vol: 634318360
[14:52:22] 000001.SS -> 4031.072021484375 | Vol: 634318360
[14:52:27] 000001.SS -> 4030.234619140625 | Vol: 695655860
[14:52:34] 000001.SS -> 4030.234619140625 | Vol: 695655860
[14:52:39] 000001.SS -> 4029.59130859375 | Vol: 716199960

In [7]:
# 实例3：获取日内历史分钟数据
symbol3 = ["BTC-USD"]
data3 = yf.download(symbol3, period="1d", interval="1m", progress=False)
data3

/var/folders/2_/cdsnq6qs41752yj0rh6g0npr0000gn/T/ipykernel_1918/2091118389.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data3 = yf.download(symbol3, period="1d", interval="1m", progress=False)

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Datetime,,,,,
2026-02-01 00:00:00+00:00,78655.093750,78655.093750,78655.093750,78655.093750,0
2026-02-01 00:01:00+00:00,78605.070312,78605.070312,78605.070312,78605.070312,0
2026-02-01 00:02:00+00:00,78576.781250,78576.781250,78576.781250,78576.781250,0
2026-02-01 00:09:00+00:00,78987.562500,78987.562500,78987.562500,78987.562500,782860288
2026-02-01 00:10:00+00:00,79050.007812,79050.007812,79050.007812,79050.007812,212951040
...,...,...,...,...,...
2026-02-01 15:01:00+00:00,78104.601562,78104.601562,78104.601562,78104.601562,449658880
2026-02-01 15:03:00+00:00,78086.914062,78086.914062,78086.914062,78086.914062,0
2026-02-01 15:04:00+00:00,77935.882812,77935.882812,77935.882812,77935.882812,466165760
2026-02-01 15:05:00+00:00,77881.921875,77881.921875,77881.921875,77881.921875,205471744
2026-02-01 15:06:00+00:00,77908.648438,77908.648438,77908.648438,77908.648438,0

In [8]:
symbol4 = ["000001.SS"]
data4 = yf.download(symbol4, period="1d", interval="1m", progress=False)
data4

/var/folders/2_/cdsnq6qs41752yj0rh6g0npr0000gn/T/ipykernel_1918/1061250317.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data4 = yf.download(symbol4, period="1d", interval="1m", progress=False)

Price,Close,High,Low,Open,Volume
Ticker,000001.SS,000001.SS,000001.SS,000001.SS,000001.SS
Datetime,,,,,
2026-01-30 01:30:00+00:00,4135.465820,4135.465820,4132.812988,4132.812988,0
2026-01-30 01:31:00+00:00,4150.133301,4150.133301,4137.296875,4137.296875,1924938900
2026-01-30 01:32:00+00:00,4149.916016,4150.080078,4147.333496,4150.080078,0
2026-01-30 01:33:00+00:00,4152.280273,4152.850098,4150.606934,4150.606934,956004000
2026-01-30 01:34:00+00:00,4146.861816,4152.416504,4146.861816,4152.416504,1429113400
...,...,...,...,...,...
2026-01-30 06:53:00+00:00,4120.077148,4120.490234,4119.859375,4119.859375,350121200
2026-01-30 06:54:00+00:00,4120.276367,4120.571777,4120.208496,4120.239746,324704300
2026-01-30 06:55:00+00:00,4119.863281,4120.806152,4119.863281,4120.399902,398371600
2026-01-30 06:56:00+00:00,4119.333496,4119.992188,4119.026367,4119.992188,468222200
2026-01-30 06:57:00+00:00,4119.005371,4119.258301,4118.421875,4119.258301,189573800